name: Test CI/CD

on:
  push:
    branches: [main, backend, frontend]
  pull_request:
    branches: [main, backend, frontend]

jobs:
  frontend-check:
    name: Build React App
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run dev

  backend-check:
    name: Build Spring Boot App
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: "23"
          distribution: "correto"

      - name: Build with maven
        run: ./mbnw clean package

      - name: Run tests - spring goat
        run: ./mbnw test
